name: gl
version: "1.0.1"
description: Dart GLES2 bindings
authors:
  - John McDole <codefu@google.com>
  - Jason Daly <dalyj@google.com>
  - Michael McLennan <nefario@google.com>
  - Harry Stern <hstern@google.com>
homepage:
environment:
  sdk: ">=1.0.0 <=2.0.0"
dev_dependencies:
  #glfw: any  # for examples in example/dart_example/ - needs to symlink locally
  glfw:
    path: ../dart-glfw
  ccompile: "^0.2.10"
  path: "^1.3.9"
