name: gl
version: "1.0.3-dev"
description: Dart GLES2 bindings
authors:
  - John McDole <codefu@google.com>
  - Jason Daly <dalyj@google.com>
  - Michael McLennan <nefario@google.com>
  - Harry Stern <hstern@google.com>
homepage:
environment:
  sdk: ">=2.0.0-dev.36.0 <3.0.0"
dev_dependencies:
  args: ^0.13.7
  ccompile: "^0.2.10"
  #glfw: any  # for examples in example/dart_example/ - needs to symlink locally
  glfw:
    path: ../dart-glfw
  path: ^1.4.1
